### ISSUE TITLE
Job fails if repo name includes UPPER CASE leters

### ISSUE THREAD

**Issue by TheHolm** [macbre/push-to-ghcr#12]
Build Job fails if repo includes a upper case letters as my one.  
```
Building the Docker image: ghcr.io/TheHolm/meraki-dashboard-promethus-exporter:latest ...
  invalid argument "ghcr.io/TheHolm/meraki-dashboard-promethus-exporter:latest" for "-t, --tag" flag: invalid reference format: repository name must be lowercase
  See 'docker build --help'.
  Error: Process completed with exit code 125.
```
Problem lays in line 71 of action.yaml
```--tag ${{ inputs.repository }}/${{ inputs.image_name }}:${COMMIT_TAG} ```

I'm not sure how to fix it. Is it possible to use something like ${{ inputs.repository | lower }} in action syntax.

**Comment by macbre** [comment]
Thanks for this report!

**Comment by macbre** [comment]
In the meantime you can do the following (provide a custom value for `image_name`):

```yaml
      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: theholm/meraki-dashboard-promethus-exporter
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by kindofluke** [comment]
Another workaround is to add a step that creates a new environment variable. 

```
jobs:
  docker_publish:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      # https://github.com/marketplace/actions/push-to-ghcr
      - name: set lower case repo name 
        run: |
          echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ env.IMAGE_REPOSITORY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}


```
