### ISSUE TITLE
Error when using Github Actions and building with Docker 23 persists

### ISSUE THREAD

**Issue by thomaspaulin** [macbre/push-to-ghcr#33]
In #29 @tobiasc laid out screenshots and information demonstrating an error when running the action in Docker 23. #30 was intended to fix this and has since been merged to master, however, when using master per the README I continue to experience this error. 

I tried using v13, the tag associated with @tobiasc 's fix just in case but found that did not work either.

```
  docker_publish:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@v13
        with:
          image_name: ${{ github.repository }}
          image_tag: $(date +%s)
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

![push-to-ghcr-fail](https://github.com/macbre/push-to-ghcr/assets/7918983/deddd301-eb3a-4116-91b5-902555064c3b)
